### ISSUE TITLE
New feature: Allow comment items that are removed on build?

### ISSUE THREAD

**Issue by yogat3ch** [0x4447/0x4447-cli-node-grapes#15]
# My Problem

Hi @davidgatti,
How are you doing?
The lack of comment support in JSON makes it difficult to provide pointers to yourself or others unfamiliar with a project when they look at the CloudFormation JSON. What if grapes enabled commenting via the mechanism described below?

# Solution

Add a processing step that removes any named item entitled `"_comment":` or `"__comment_:` such that the CFN files could be commented out in the repository but readied for deployment in the CloudFormation.json file. 
The [`traverse` package](https://socket.dev/npm/package/traverse) might be useful here.

**Comment by davidgatti** [comment]
Hi @yogat3ch CloudFormation already has the `Description` Key: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html
